n_conditions: 1
dataset: ['cifar10']
dataset_dir: ['/work/MachineLearning/dataset/CIFAR-10/python/cifar-10-batches-py/']
n_epoch: [200]
n_minibatch: [64]
optimizer: ['Adam']
learning_rate: [0.0001]
weight_decay: [0.0001]
conv_channels: [[64, 128, 256]]
conv_kernel_size: [[3, 3, 3]]
pool_size: [[2, 2]]
fc_channels: [[512]]
dropout_rate: [0.5]

