n_conditions: 4
dataset: ['cifar10', 'cifar10', 'cifar10', 'cifar10']
n_epoch: [32, 32, 32, 32]
n_minibatch: [32, 32, 32, 32]
optimizer: ['Adam', 'Adam', 'Adam', 'Adam']
learning_rate: [0.001, 0.001, 0.001, 0.001]
weight_decay: [0.001, 0.01, 0.1, 0.0]
