n_conditions: 2
dataset: ['cifar10', 'cifar10']
n_epoch: [64, 64]
n_minibatch: [32, 32]
optimizer: ['Adam', 'Adam']
learning_rate: [0.001, 0.001]
weight_decay: [0.001, 0.001]
conv_channels: [[32, 64], [32, 64, 96]]
conv_kernel_size: [[3, 3], [3, 3, 3]]
